# -------------------------
# Stage 1: Builder
# -------------------------
FROM dunglas/frankenphp:php8.4 AS builder

RUN apt-get update --allow-releaseinfo-change && apt-get install -y --no-install-recommends \
    curl unzip nano git ca-certificates gnupg wget \
    libpq-dev libonig-dev libssl-dev libxml2-dev \
    libcurl4-openssl-dev libicu-dev libzip-dev libexif-dev \
    libjpeg62-turbo-dev libpng-dev libfreetype6-dev \
 && curl -fsSL https://deb.nodesource.com/setup_20.x | bash - \
 && apt-get install -y nodejs \
 && docker-php-ext-configure gd --with-freetype --with-jpeg \
 && docker-php-ext-install -j$(nproc) \
    pcntl pdo_mysql pdo_pgsql pgsql opcache intl zip bcmath soap exif gd \
 && pecl install redis \
 && docker-php-ext-enable redis \
 && apt-get autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

#  && pecl install grpc \
#  && docker-php-ext-enable grpc \

WORKDIR /app
COPY . .

RUN if [ -f "composer.lock" ]; then rm composer.lock; fi
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer \
    && if [ "$APP_ENV" = "production" ]; then \
         COMPOSER=composer_hq.json composer install --no-dev --optimize-autoloader --no-interaction --no-progress --prefer-dist --no-scripts; \
    else \
         COMPOSER=composer_hq.json composer install --optimize-autoloader --no-interaction --no-progress --prefer-dist --no-scripts; \
    fi

# # -------------------------
# # Stage 2: Production
# # -------------------------
FROM builder AS production

COPY ./docker/production/entrypoint.hq.sh /usr/local/bin/entrypoint.hq.sh
RUN chmod +x /usr/local/bin/entrypoint.hq.sh

COPY ./storage /app/storage-init
COPY --from=builder /app /app
COPY --from=builder /usr/local/lib/php/extensions/ /usr/local/lib/php/extensions/
COPY --from=builder /usr/local/etc/php/conf.d/ /usr/local/etc/php/conf.d/
COPY --from=builder /usr/local/bin/docker-php-ext-* /usr/local/bin/

RUN mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

# Pastikan storage & bootstrap/cache bisa ditulis
RUN mkdir -p /app/storage /app/bootstrap/cache \
    && chown -R www-data:www-data /app/storage /app/bootstrap /app/bootstrap/cache \
    && chmod -R 775 /app/storage /app/bootstrap/cache

WORKDIR /app
USER www-data

ENTRYPOINT ["/usr/local/bin/entrypoint.hq.sh"]
EXPOSE 9001
# CMD dihapus, nanti diatur di docker-compose

# # -------------------------
# # Stage 3: Development
# # -------------------------
FROM production AS development

USER root

COPY ./docker/common/frankenphp-fpm.conf /etc/frankenphp/conf.d/
COPY ./docker/development/entrypoint.hq.sh /usr/local/bin/entrypoint.hq.sh
RUN chmod +x /usr/local/bin/entrypoint.hq.sh

ENTRYPOINT ["/usr/local/bin/entrypoint.hq.sh"]
EXPOSE 9001
# CMD dihapus, nanti diatur di docker-compose
